name: run_tests
on: [push]
jobs:
   run_tests:
    runs-on: ubuntu-latest
    steps:
     - run: |
        rm main.py
        wget https://github.com/YuliaGURevichh/task3/blob/master/main.py
        python main.py
      