name: run_tests
on: [push]
jobs:
   run_tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
        wget https://github.com/YuliaGURevichh/task3/blob/master/main.py
        wget https://github.com/YuliaGURevichh/task3/blob/master/tests.py
        output=$(python main.py)
      